- betadocs/Building_Your_Application/Configuring/next.config.js.md
> next.config.js 1차 번역 완료

- betadocs/API_Reference/Server_Component_Functions/notFound.md
> Server Component Functions / notFound 번역완료

- betadocs/API_Reference/Client_Component_Hooks/Clent_Component_Hooks.md
create path file and stabledocs little bit change
> create path file and stabledocs little bit change

- betadocs/API_Reference/Client_Component_Hooks/usePathname.md
- betadocs/API_Reference/Client_Component_Hooks/useSearchParams.md
- betadocs/API_Reference/Client_Component_Hooks/useSelectedLayoutSegment.md
- betadocs/API_Reference/Client_Component_Hooks/useSelectedLayoutSegments.md
- betadocs/Building_Your_Application/Configuring/Turbopack.md
- betadocs/Building_Your_Application/Data_Fetching/API_Routes.md
Configuring/Turbopack (Alpha)
API Reference / Client Component Hooks / useSelectedLayoutSegment
API Reference / Client Component Hooks / useSelectedLayoutSegments
API Reference / Client Component Hooks / usePathname
Data Fetching / API Routes
번역 완료
> Beta turbopack

- betadocs/Building_Your_Application/Styling/CSS_Modules.md
- betadocs/Building_Your_Application/Styling/CSS_in_JS.md
- betadocs/Building_Your_Application/Styling/Global_Styles.md
- betadocs/Building_Your_Application/Styling/Tailwind_CSS.md
CSS-in-JS 번역, 파일들 간의 link 설정 완.
부모 파일 링크는 Styling 안의 파일들 번역이 다 끝난 뒤에 진행하겠습니다.
> Building Your Application / Styling / CSSInJS

- nextjsdocs/APIReference/Functions/useParams.md
- nextjsdocs/APIReference/Functions/useRouter.md
- nextjsdocs/APIReference/Functions/useSearchParams.md
Routing.md 링크 필요하신 분 있을 수 있어 일단 파일만 만들어 PR 올립니다!
> Routing.md 파일에 추가

- nextjsdocs/BuildingYourApplication/Configuring/TypeScript.md
Building Your Application > Configuring > TypeScript 번역 완료하여 PR 합니다. 
감사합니다. 
(SEB_FE_44_박영미)
> Building Your Application > Configuring > TypeScript 번역 완료 PR

- nextjsdocs/APIReference/next.config.jsOptions/pageExtensions.md
nextjsdocs/nextConfig.jsOptions/pageExtensions.md 번역완료
> nextjsdocs/nextConfig.jsOptions/pageExtensions.md 번역완료

- nextjsdocs/APIReference/next.config.jsOptions/compress.md
> compress 번역 완료

- nextjsdocs/APIReference/next.config.jsOptions/headers.md
headers 번역 완료 했습니다 :) 확인 부탁드려요 !
> headers 번역 완료

- nextjsdocs/BuildingYourApplication/Configuring/Environment_Variables.md
- nextjsdocs/BuildingYourApplication/Configuring/src_Directory.md
Building Your Application > Configuring > Environment Variables 
Building Your Application > Configuring > src Directory 
위 두 문서 번역 완료하여 PR 보냅니다. 
감사합니다.
> 📝 Environment Variables &  src Directory 번역 완료

- nextjsdocs/BuildingYourApplication/Optimizing/Analytics.md
- nextjsdocs/BuildingYourApplication/Optimizing/Instrumentation.md
- nextjsdocs/BuildingYourApplication/Optimizing/Lazy_Loading.md
- nextjsdocs/BuildingYourApplication/Optimizing/OpenTelemetry.md
- nextjsdocs/BuildingYourApplication/Optimizing/Static_Assets.md
Optimizing 개편 후 번역 완료
Building Your Application > Optimizing > Static Assets
Building Your Application > Optimizing > Lazy Loading
Building Your Application > Optimizing > Analytics
Building Your Application > Optimizing > OpenTelemetry
Building Your Application > Optimizing > Instrumentation
> Optimizing 개편 후 번역 완료

- nextjsdocs/BuildingYourApplication/Rendering/Edge_and_Node.js_Runtimes.md
Edge and Node.js Runtimes 번역 완료 했습니다. 확인 부탁드려요!! :)
> Edge and Node.js Runtimes 번역 완료

- nextjsdocs/APIReference/Functions/revalidatePath.md
- nextjsdocs/APIReference/Functions/revalidateTag.md
- nextjsdocs/APIReference/next.config.jsOptions/turbo.md
> revalidatePath, revalidateTag, turbo 번역 완료

- nextjsdocs/APIReference/Functions/useReportWebVitals.md
- nextjsdocs/BuildingYourApplication/Upgrading/App_Router_Migration.md
- useReportWebVitals 문서 번역 완료하였습니다.
- 이전에 번역했던 App Router Migration 문서의 공식 문서 링크를 수정하였습니다.
이번 주도 고생 많으셨습니다!
> useReportWebVitals 번역 완료

- nextjsdocs/APIReference/Next.jsCLI.md
> Next.js CLI 번역완료

- nextjsdocs/APIReference/FileConventions/Route_Segment_Config.md
- nextjsdocs/APIReference/FileConventions/error.js.md
- nextjsdocs/APIReference/FileConventions/layout.js.md
- nextjsdocs/APIReference/FileConventions/loading.js.md
- nextjsdocs/APIReference/FileConventions/not-found.js.md
- nextjsdocs/APIReference/FileConventions/page.js.md
- nextjsdocs/APIReference/FileConventions/route.js.md
APIReference / FileConventions 파트 중 하기 부분 번역 완료 
* error.js
* layout.js
* loading.js
* not-found.js
* page.js
* route.js
* Route Segment Config.js
확인 부탁드립니다.
> API_Reference / File_Conventions 번역 완료 

- nextjsdocs/BuildingYourApplication/Configuring/ESLint.md
> Configuring / ESLint 번역완료

- README.md
- nextjsdocs/GettingStarted/Installation.md
- nextjsdocs/GettingStarted/Project_Structure.md
- nextjsdocs/GettingStarted/React_Essentials.md
번역 Getting Started 완료했습니다. 확인 부탁 드려요!
> Docs: Next.js 문서 번역 Getting Started 완료

- nextjsdocs/APIReference/Functions/useRouter.md
- **useRouter.md > "Migrating from the pages directory" 중 뒤바뀐 내용이 있어 수정함**
> useRouter.md > 뒤바뀐 내용 수정
